### ISSUE TITLE
Doesn't build on riscv32i-unknown-none-elf without default features (regression 0.7.10)

### ISSUE THREAD

**Issue by Kriskras99** [japaric/heapless#271]
When adding `heapless` as a dependency:
```toml
[dependencies]
heapless = { version = "=0.7.10", default-features = false, features = [] }
```
it does not build:
```
   Compiling heapless v0.7.10
error[E0432]: unresolved import `atomic_polyfill`
  --> /home/kriskras99/.cargo/registry/src/github.com-1ecc6299db9ec823/heapless-0.7.10/src/spsc.rs:90:5
   |
90 | use atomic_polyfill::{AtomicUsize, Ordering};
   |     ^^^^^^^^^^^^^^^ use of undeclared crate or module `atomic_polyfill`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `heapless` due to previous error
```
This regression was introduced with version `0.7.10` (aka it works with `version = "=0.7.9"`)
Also see [the Rust Crypto issue](https://github.com/RustCrypto/AEADs/issues/398).

**Comment by Kriskras99** [comment]
I've bisected the change to commit 63c0370d690ba7a9121754c3ecd361db6088b694
